# Dependabot configuration.
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "uv" # pyproject.toml + uv.lock
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker" # base images in Dockerfile
    directory: "/"
    schedule:
      interval: "weekly"
