name: "[Analyzer] New analyzer request"
description: Suggest a new analyzer
title: "[Analyzer] "
labels: ["analyzer", "priority 2"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Analyzer tool
      description: What problem does this feature solve?
      placeholder: Describe the use case
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: How should it work?
    validations:
      required: true
